In [5]:
import numpy as np

In [8]:
subject_file = "../Datasets/HCP_motor-task_12-subjects/sub-102008_TS.txt"
length = 100
ROIs = [-1]

In [18]:
name_subject = subject_file.split("/")[-1].split("_TS")[0] + '_Length-' + str(length)
print(f"Participant ID: {name_subject}")

# Load time series from subject -- dims: time-points X total-ROIs
time_series = np.genfromtxt(subject_file)# TODO: Add compatibility, delimiter='\t')
if np.isnan(time_series[:,0]).all():
    time_series = time_series[:,1:] # First column is dropped due to Nan
limit = int(time_series.shape[0]*0.01*length)
print(time_series.shape[0])

# ROIs from input command
ROIs = list(range(time_series.shape[-1])) if ROIs[0] == -1 else [roi-1 for roi in ROIs]
ROIs = ROIs[:5]

# Time series to analyse -- dims: ROIs X 1 X time-points
TS2analyse = np.expand_dims(
    np.array([time_series[:limit,roi] for roi in ROIs]), axis=1
)

print(f"TS2analyse.shape: {TS2analyse.shape}")
print(f"No. ROIs: {len(ROIs)} -> No. pairs: {int(0.5 * len(ROIs) * (len(ROIs) - 1))}\n")

Participant ID: sub-102008_Length-100
284
TS2analyse.shape: (5, 1, 284)
No. ROIs: 5 -> No. pairs: 10



In [21]:
print(time_series[:10, :3])

[[-1.7170555e+01  9.7541650e+00 -3.2609444e+01]
 [-1.4019283e+01  1.7011324e+01 -4.8442904e+01]
 [-1.1907902e+01  1.8373649e+01 -6.0465973e+01]
 [-1.0905414e+01  1.4681274e+01 -6.2450480e+01]
 [-1.1113604e+01  8.5082250e+00 -5.2713537e+01]
 [-1.2670258e+01  3.1339070e+00 -3.4569214e+01]
 [-1.5554468e+01  1.2482920e+00 -1.4670972e+01]
 [-1.9287836e+01  3.8620940e+00 -2.0840000e-03]
 [-2.2753117e+01  9.8642590e+00  5.2041660e+00]
 [-2.4264374e+01  1.6363053e+01  1.3412190e+00]]
